packages:
  - 'packages/*'

catalog:
  '@slidev/cli': ^0.49.29
  '@slidev/types': ^0.49.29
  'codemirror-theme-vars': ^0.1.2
  'prism-theme-vars': ^0.2.5
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
  'playwright-chromium': ^1.48.2
  'vue': ^3.5.12