name: Check pull request

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'page/**'

permissions:
  statuses: write
  contents: read
  pull-requests: write

defaults:
  run:
    working-directory: page


jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install
        run: |
          pnpm install

      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          workdir: page
          fail_on_error: 'true'