name: Slide Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - 'resource/**'

defaults:
  run:
    working-directory: resource

jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true
      AWS_REGION: auto
      S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
      S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

        # pnpmのインストール
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

        # Node.jsのインストール
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

        # パッケージのインストール
      - name: Install dependencies
        run: pnpm install

        # Templateの削除
      - name : Remove template
        run: |
          rm -rf packages/template

        #依存関係のインストール
      - name : Install dependencies
        run: |
          sudo apt update && sudo apt install -y \
          language-pack-ja \
          fontconfig \
          fonts-ipafont \
          fonts-noto-cjk \
          && sudo rm -rf /var/lib/apt/lists/*

        # フォントのインストール pdf,screenshotの日本語対応
      - name : Install font
        env:
          LANG: ja_JP:UTF-8
        run: |
          sudo fc-cache -fv && \
          fc-list

        # Chromeのインストール playwrightの依存関係
      - name : Install Chrome
        run: |
          pnpm dlx @playwright/test@latest install --with-deps

      - name: Fix permissions
        run: |
          chmod +x ./packages/**/upload.sh

        # S3へのアップロード
      - name: Upload to S3
        run: |
          pnpm run publish
